# Generated by Django 3.1.2 on 2021-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
